# Basic Site Settings
title: "Dr. Ouail Zakary | Computational Chemist"
description: "Research in quantum chemistry, machine learning for molecular systems, and NMR parameter models."
url: "https://ozakary.github.io"  # Your GitHub Pages URL
baseurl: ""  # Leave blank unless you're using a subpath
author: "Dr. Ouail Zakary"

# Theme Settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

# Social Media Links
social_links:
  linkedin: "https://www.linkedin.com/in/ouail-zakary-a63a521b9"
  github: "https://github.com/ozakary"
  google_scholar: "https://scholar.google.com/citations?user=kKUFATIAAAAJ&hl=fr"
  researchgate: "https://www.researchgate.net/profile/Ouail-Zakary"

# Navigation Bar Links
navbar:
  - name: "Home"
    link: "/"
  - name: "Research"
    link: "/research"
  - name: "Projects"
    link: "/projects"
  - name: "CV"
    link: "/cv"
  - name: "Contact"
    link: "/contact"

# Plugins (Optional)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build Settings
markdown: kramdown
highlighter: rouge
